### ISSUE TITLE
[Feature request] Connection pool

### ISSUE THREAD

**Issue by tamakisquare** [oeegor/apns2-client#7]
Excerpt from the [official docs](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) on _Best Practices for Managing Connections_,

> **Keep your connections with APNs open across multiple notifications; do not repeatedly open and close connections. APNs treats rapid connection and disconnection as a denial-of-service attack**. You should leave a connection open unless you know it will be idle for an extended period of time—for example, if you only send notifications to your users once a day, it is acceptable practice to use a new connection each day.

I think it's the best for _apns2-client_ library to conform to this best practice, in order to avoid the possibility of having the services built with the library being seeing as a denial-of-service attack and thus interruption to those services. Therefore, I think we should add a connection pool for managing the reuse of open connections to this library.

Thanks for developing this library. It has been working great for me and its code is easy to read and follow.

**Comment by oeegor** [comment]
Hi @tamakisquare, 
An instance of `APNSClient` reuses its connection so sending multiple messages using one instance of a client will use only one connection. So a best practice from your message is respected.

**Comment by tamakisquare** [comment]
@oeegor, I see your point. The use case I have in mind, however, is not sending multiple messages all at once but multiple messages throughout a time period. Think of instant messaging apps, which need to support realtime push notification. If I were to send a couple messages to a friend using a messaging app that relies on the current apns2-client, the number of connection open&close would be equal to the number of messages I sent.

**Comment by oeegor** [comment]
So in this case I think one would have `APNSClient` instance as a singleton in one's web app and that singleton instance will be used to send occasional push notifications.

**Comment by tamakisquare** [comment]
@oeegor, what you said puzzled me as I have been using singleton all along and then I realized that I confused your library with _Pr0Ger/PyAPNs2_. My request is meant for _Pr0Ger/PyAPNs2_. Sorry for the trouble.
